create sequence hibernate_sequence start with 1 increment by 1;
create table author (id bigint not null, name varchar(255), primary key (id));
create table blacklist (id bigint not null, ispaid bit, price bigint, reader_id bigint, specific_book_id bigint, primary key (id));
create table book (id bigint not null, name varchar(255), price int check (price<=10000 AND price>=1000), year int check (year<=2020 AND year>=1900), author_id bigint not null, genre_id bigint not null, language_id bigint not null, publisher_id bigint not null, primary key (id));
create table city (id bigint not null, name varchar(255), primary key (id));
create table genre (id bigint not null, name varchar(255), primary key (id));
create table language (id bigint not null, name varchar(255), primary key (id));
create table librarian (id bigint not null, password varchar(255), username varchar(255), primary key (id));
create table publisher (id bigint not null, name varchar(255), city_id bigint, primary key (id));
create table reader (id bigint not null, address varchar(255), behavior_rank int, date_of_birth date, first_name varchar(255), last_name varchar(255), phone varchar(255), primary key (id));
create table specific_book (id bigint not null, in_place bit, rank varchar(255), room varchar(255), shelf varchar(255), unique_code varchar(255), book_id bigint not null, primary key (id));
create table specific_book_reader (id bigint not null, date_of_issue date, is_return bit, real_return_date date, return_date date, reader_id bigint not null, specific_book_id bigint not null, primary key (id));
alter table specific_book add constraint UKgedt7uahkiqt7tp4s5947f39l unique (shelf, rank, room);
alter table blacklist add constraint FK36qxcpp6t2fqmu6a1ncbn7fhk foreign key (reader_id) references reader;
alter table blacklist add constraint FKfu6e37y5j07w388mq2tcm8du2 foreign key (specific_book_id) references specific_book;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author;
alter table book add constraint FKm1t3yvw5i7olwdf32cwuul7ta foreign key (genre_id) references genre;
alter table book add constraint FKmrhfp9wfi5dy4bwl87bx8ivua foreign key (language_id) references language;
alter table book add constraint FKgtvt7p649s4x80y6f4842pnfq foreign key (publisher_id) references publisher;
alter table publisher add constraint FKeldjg9rrmd96hdi8id1e28gv3 foreign key (city_id) references city;
alter table specific_book add constraint FKg37ijl87y6hacuevb56vlsynt foreign key (book_id) references book;
alter table specific_book_reader add constraint FK4cwkn41l23e5u1mdmc5q13d60 foreign key (reader_id) references reader;
alter table specific_book_reader add constraint FKa3iexfyquqgvtm7xm174ltiva foreign key (specific_book_id) references specific_book;